version: '2'
services:
    jerkaero-app:
        image: jerkaero
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jerkaero-mysql:3306/jerkaero?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jerkaero-elasticsearch:9300
        ports:
            - 8080:8080
    jerkaero-mysql:
        extends:
            file: mysql.yml
            service: jerkaero-mysql
    jerkaero-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jerkaero-elasticsearch
